/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * API Documentation
 * Dokumentacja API aplikacji
 * OpenAPI spec version: 1.0
 */
export interface Role {
  id?: number;
  name?: string;
}

export interface User {
  id?: number;
  username?: string;
  email?: string;
  password?: string;
  enabled?: boolean;
  createdAt?: string;
  roles?: Role[];
}

export interface Profile {
  id?: number;
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  user?: User;
}

export interface Comment {
  text?: string;
  createdAt?: string;
  event?: Event;
  user?: User;
  id?: number;
}

export interface Event {
  id?: number;
  title?: string;
  description?: string;
  eventDate?: string;
  location?: string;
  user?: User;
  comments?: Comment[];
}

export type ParticipationStatus = typeof ParticipationStatus[keyof typeof ParticipationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationStatus = {
  REGISTERED: 'REGISTERED',
  CANCELLED: 'CANCELLED',
} as const;

export interface Participation {
  id?: number;
  event?: Event;
  user?: User;
  status?: ParticipationStatus;
  registeredAt?: string;
}

/**
 * Data requires to create user
 */
export interface UserDto {
  /** Email Adress */
  email: string;
  /** Username */
  username: string;
  /** Password */
  password: string;
  /** Enabled */
  enabled: boolean;
  /** Created at */
  createdAt: string;
  /** User Roles */
  roles: Role[];
}

/**
 * Data requires to register user 
 */
export interface UserRegisterDto {
  /** Email Adress */
  email: string;
  /** Username */
  username: string;
  /** Password */
  password: string;
}

/**
 * Data requires to create role
 */
export interface RoleDto {
  /** Name */
  name: string;
  /** Users */
  users?: User[];
}

/**
 * Data requires to create profile
 */
export interface ProfileDto {
  /** First Name */
  firstName?: string;
  /** Last Name */
  lastName?: string;
  /** Phone number */
  phoneNumber?: string;
  user?: User;
}

/**
 * Participation status
 */
export type ParticipationDtoStatus = typeof ParticipationDtoStatus[keyof typeof ParticipationDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipationDtoStatus = {
  REGISTERED: 'REGISTERED',
  CANCELLED: 'CANCELLED',
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
} as const;

export interface ParticipationDto {
  event: Event;
  user: User;
  /** Participation status */
  status?: ParticipationDtoStatus;
  /** Registration timestamp */
  registeredAt?: string;
}

export interface EventDto {
  /** Title */
  title?: string;
  /** Description */
  description?: string;
  /** Event date and time */
  eventDate: string;
  /** Event location */
  location?: string;
  user?: User;
  /** Event comments */
  comments?: Comment[];
}

/**
 * Data requires to create comment
 */
export interface CommentDto {
  /** Text comment */
  text?: string;
  event?: Event;
  user?: User;
}

/**
 * Dane potrzebne do autoryzacji
 */
export interface AuthorizationLoginDto {
  /** Username */
  username: string;
  /** Password */
  password: string;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface PageEvent {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  size?: number;
  content?: Event[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  empty?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
  paged?: boolean;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export type GetUserById200 = { [key: string]: unknown };

export type GetUserById400 = {[key: string]: string};

export type GetUserById404 = { [key: string]: unknown };

export type UpdateUser200 = { [key: string]: unknown };

export type UpdateUser400 = {[key: string]: string};

export type UpdateUser404 = { [key: string]: unknown };

export type DeleteUser200 = { [key: string]: unknown };

export type DeleteUser400 = {[key: string]: string};

export type DeleteUser404 = { [key: string]: unknown };

export type GetUserRoles200 = { [key: string]: unknown };

export type GetUserRoles400 = {[key: string]: string};

export type AssignRoles200 = { [key: string]: unknown };

export type AssignRoles400 = {[key: string]: string};

export type ChangePasswordBody = {[key: string]: string};

export type ChangePassword200 = { [key: string]: unknown };

export type ChangePassword400 = {[key: string]: string};

export type GetRoleById200 = { [key: string]: unknown };

export type GetRoleById400 = {[key: string]: string};

export type GetRoleById404 = { [key: string]: unknown };

export type UpdateRole200 = { [key: string]: unknown };

export type UpdateRole400 = {[key: string]: string};

export type UpdateRole404 = { [key: string]: unknown };

export type DeleteRole200 = { [key: string]: unknown };

export type DeleteRole400 = {[key: string]: string};

export type DeleteRole404 = { [key: string]: unknown };

export type GetProfileById200 = { [key: string]: unknown };

export type GetProfileById400 = {[key: string]: string};

export type GetProfileById404 = { [key: string]: unknown };

export type UpdateProfile200 = { [key: string]: unknown };

export type UpdateProfile400 = {[key: string]: string};

export type UpdateProfile404 = { [key: string]: unknown };

export type DeleteProfile200 = { [key: string]: unknown };

export type DeleteProfile400 = {[key: string]: string};

export type DeleteProfile404 = { [key: string]: unknown };

export type GetParticipationById400 = {[key: string]: string};

export type UpdateParticipation400 = {[key: string]: string};

export type DeleteParticipation400 = {[key: string]: string};

export type GetEventById400 = {[key: string]: string};

export type UpdateEvent400 = {[key: string]: string};

export type DeleteEvent400 = {[key: string]: string};

export type GetCommentById200 = { [key: string]: unknown };

export type GetCommentById400 = {[key: string]: string};

export type GetCommentById404 = { [key: string]: unknown };

export type UpdateComment200 = { [key: string]: unknown };

export type UpdateComment400 = {[key: string]: string};

export type UpdateComment404 = { [key: string]: unknown };

export type DeleteComment200 = { [key: string]: unknown };

export type DeleteComment400 = {[key: string]: string};

export type DeleteComment404 = { [key: string]: unknown };

export type GetAllUsers400 = {[key: string]: string};

export type CreateUser200 = { [key: string]: unknown };

export type CreateUser400 = {[key: string]: string};

export type AddRole200 = { [key: string]: unknown };

export type AddRole400 = {[key: string]: string};

export type RemoveRole200 = { [key: string]: unknown };

export type RemoveRole400 = {[key: string]: string};

export type RegisterUser201 = { [key: string]: unknown };

export type RegisterUser400 = {[key: string]: string};

export type GetAllRoles400 = {[key: string]: string};

export type CreateRole201 = { [key: string]: unknown };

export type CreateRole400 = {[key: string]: string};

export type GetRolesByNames400 = {[key: string]: string};

export type CreateProfile201 = { [key: string]: unknown };

export type CreateProfile400 = {[key: string]: string};

export type GetAllParticipations400 = {[key: string]: string};

export type CreateParticipation400 = {[key: string]: string};

export type GetAllEvents400 = {[key: string]: string};

export type CreateEvent400 = {[key: string]: string};

export type CreateComment201 = { [key: string]: unknown };

export type CreateComment400 = {[key: string]: string};

export type Login200 = { [key: string]: unknown };

export type Login400 = {[key: string]: string};

export type DeactivateUser200 = { [key: string]: unknown };

export type DeactivateUser400 = {[key: string]: string};

export type ActivateUser200 = { [key: string]: unknown };

export type ActivateUser400 = {[key: string]: string};

export type UpdateParticipationStatusParams = {
status: UpdateParticipationStatusStatus;
};

export type UpdateParticipationStatusStatus = typeof UpdateParticipationStatusStatus[keyof typeof UpdateParticipationStatusStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateParticipationStatusStatus = {
  REGISTERED: 'REGISTERED',
  CANCELLED: 'CANCELLED',
} as const;

export type UpdateParticipationStatus400 = {[key: string]: string};

export type CheckUserHasRole200 = {[key: string]: boolean};

export type CheckUserHasRole400 = {[key: string]: string};

export type GetUserByUsername200 = { [key: string]: unknown };

export type GetUserByUsername400 = {[key: string]: string};

export type GetUserByEmail200 = { [key: string]: unknown };

export type GetUserByEmail400 = {[key: string]: string};

export type GetRolesByUserId400 = {[key: string]: string};

export type GetAllRolesByOrderByNameAsc400 = {[key: string]: string};

export type GetRoleByName200 = { [key: string]: unknown };

export type GetRoleByName400 = {[key: string]: string};

export type ExistsByNameParams = {
name: string;
};

export type ExistsByName400 = {[key: string]: string};

export type GetAllProfiles400 = {[key: string]: string};

export type GetParticipationByUserId400 = {[key: string]: string};

export type GetParticipationByStatus400 = {[key: string]: string};

export type GetParticipationsByRegisteredAtBeforeParams = {
date: string;
};

export type GetParticipationsByRegisteredAtBefore400 = {[key: string]: string};

export type GetParticipationByRegisteredAtParams = {
date: string;
};

export type GetParticipationByRegisteredAt400 = {[key: string]: string};

export type GetParticipationsByRegisteredAtAfterParams = {
date: string;
};

export type GetParticipationsByRegisteredAtAfter400 = {[key: string]: string};

export type GetParticipationByEventId400 = {[key: string]: string};

export type GetEventByUserId400 = {[key: string]: string};

export type GetEventsByTitle400 = {[key: string]: string};

export type SearchEventsByKeywordParams = {
keyword: string;
};

export type SearchEventsByKeyword400 = {[key: string]: string};

export type GetEventsByLocation400 = {[key: string]: string};

export type GetEventsBeforeDateParams = {
date: string;
};

export type GetEventsBeforeDate400 = {[key: string]: string};

export type GetEventsBeforeDateSortedParams = {
date: string;
order?: string;
};

export type GetEventsBeforeDateSorted400 = {[key: string]: string};

export type GetEventsBeforeDateWithKeywordParams = {
date: string;
keyword: string;
};

export type GetEventsBeforeDateWithKeyword400 = {[key: string]: string};

export type GetPagedEventsBeforeDateParams = {
date: string;
pageable: Pageable;
};

export type GetPagedEventsBeforeDate400 = {[key: string]: string};

export type GetEventsAfterDateParams = {
date: string;
};

export type GetEventsAfterDate400 = {[key: string]: string};

export type GetEventsAfterDateSortedParams = {
date: string;
order?: string;
};

export type GetEventsAfterDateSorted400 = {[key: string]: string};

export type GetEventsAfterDateWithKeywordParams = {
date: string;
keyword: string;
};

export type GetEventsAfterDateWithKeyword400 = {[key: string]: string};

export type GetPagedEventsAfterDateParams = {
date: string;
pageable: Pageable;
};

export type GetPagedEventsAfterDate400 = {[key: string]: string};

export type GetAllComments400 = {[key: string]: string};

export type GetCommentsByUserId200 = { [key: string]: unknown };

export type GetCommentsByUserId400 = {[key: string]: string};

export type GetCommentsByEventId200 = { [key: string]: unknown };

export type GetCommentsByEventId400 = {[key: string]: string};

export type GetCommentsByCreatedAt200 = { [key: string]: unknown };

export type GetCommentsByCreatedAt400 = {[key: string]: string};

export type GetCommentsBeforeCreatedAtOrderedByTextDesc200 = { [key: string]: unknown };

export type GetCommentsBeforeCreatedAtOrderedByTextDesc400 = {[key: string]: string};

export type GetCommentsBeforeCreatedAtOrderedByTextAsc200 = { [key: string]: unknown };

export type GetCommentsBeforeCreatedAtOrderedByTextAsc400 = {[key: string]: string};

export type GetCommentsAfterCreatedAtOrderedByTextDesc200 = { [key: string]: unknown };

export type GetCommentsAfterCreatedAtOrderedByTextDesc400 = {[key: string]: string};

export type GetCommentsAfterCreatedAtOrderedByTextAsc200 = { [key: string]: unknown };

export type GetCommentsAfterCreatedAtOrderedByTextAsc400 = {[key: string]: string};

